### ISSUE TITLE
[Feature 10] Pawn class implementing Calculator interface

### ISSUE THREAD

**Issue by nawarani** [CSC207-2023Y-UofT/course-project-thechessteam#19]
Create class pawn extending pieces and implementing calculator.
implement valid moves for white and blank pawns separately.
find tiles for:
- default 1 tile vertical move
- 2 tile first move
- diagonal 1 tile attack move

Merge the above categories in potential move tiles.
If there is an ally in potential move tile, remove the tile for potential tiles.
return final valid moves.

**Comment by AscendedWise** [comment]
This issue has been completed.
