### ISSUE TITLE
[Feature 5] Pawn Promotion System

### ISSUE THREAD

**Issue by 123Chan** [CSC207-2023Y-UofT/course-project-thechessteam#3]
- Create a button in View for Pawn Promotion
- If we moved a piece, do the following: if the piece moved was (a) a pawn and (b) reached the end of the board, activate the button for Pawn Promotion

- Take input from the Pawn Promotion button and update the board accordingly
- Call Checkmate System at the end of Pawn Promotion System

**Comment by AscendedWise** [comment]
Not enough time to complete this, will not be moving forward with this issue.
