### ISSUE TITLE
[Feature 4]Move a piece

### ISSUE THREAD

**Issue by nawarani** [CSC207-2023Y-UofT/course-project-thechessteam#5]
- Registers click from view **after** a piece has been chosen
- Controller calls method to evaluate cases.
- Case 1: same or invalid spot has been clicked -> go into 'choose a piece' use case.
- Case 2: Valid move -> go into 'move a piece' use case.
- Moving a piece:
 -> Update board
 -> Check if other cases(pawn promotion, capture piece etc) are activated.
 -> Update view through presenter.
- Exit.

**Comment by AscendedWise** [comment]
This issue has been completed
